version: '3.7'

services:
  apache:
    build: './Apache'
    restart: always
    ports:
      - 6666:80
    networks: 
      - frontend
      - backend
    volumes:
      - ./index:/usr/local/apache2/htdocs

    depends_on:
      - php
      - mysql
  php:
    build: './PHP'
    restart: always
    networks: 
      - backend
    volumes:
      - ./index:/usr/local/apache2/htdocs      
  mysql:
    build: './MySQL'
    restart: always
    networks:
      - backend
    volumes:
      - ./BazaDanych:/var/lib/mysql
networks: 
  backend:
  frontend:
